import {Types} from "mongoose";
import type ICloudinaryImage from "../../../shared/model/cloudinary-image/ICloudinaryImage.js";
import type {ISO3166Alpha2Code} from "../../../shared/schema/enums/country/ISO3166Alpha2CodeEnumSchema.js";

/**
 * Represents a person with basic identifying information,
 * biography, date of birth, nationality, and an optional profile image.
 */
export interface IPerson {
    /**
     * Unique identifier for the person.
     * Typically generated by MongoDB.
     */
    readonly _id: Types.ObjectId;

    /**
     * Full name of the person.
     */
    name: string;

    /**
     * A short biography or description of the person.
     */
    biography: string;

    /**
     * Date of birth of the person.
     */
    dob: Date;

    /**
     * Nationality of the person, represented as an ISO 3166-1 alpha-2 code.
     */
    nationality: ISO3166Alpha2Code;

    /**
     * Optional profile image of the person.
     * Can be `null` if the person does not have a profile image.
     */
    profileImage?: ICloudinaryImage | null;
}

