/**
 * @file Factory for generating standardized Express CRUD routers.
 * @filename createBaseRoutes.ts
 */

import express, { type RequestHandler, type Router } from "express";
import asyncHandler from "../utility/handlers/asyncHandler.js";
import isAuth from "../../domains/authentication/middleware/isAuth.js";
import type { BaseControllerCRUDMethods } from "../controller/base-crud-controller/BaseControllerCRUDMethods.js";
import type { BaseRouteMethods, BaseRoutePathKeys } from "./BaseRoute.types.js";

/**
 * Internal mapping for binding a controller method to an Express route.
 * @template TController - Must implement {@link BaseControllerCRUDMethods}.
 */
type RoutePath<TController extends BaseControllerCRUDMethods> = {
    /** {@link BaseRoutePathKeys} used for identification and filtering. */
    key: BaseRoutePathKeys;
    /** HTTP verb (e.g., 'get', 'post'). */
    method: BaseRouteMethods;
    /** The relative URL segment. */
    path: string;
    /** The specific handler key on the {@link BaseControllerCRUDMethods} instance. */
    fn: keyof TController;
};

/**
 * Middleware configuration for automated route generation.
 * @template TController - Controller method keys used for targeted middleware.
 */
export type BaseRouteMiddleware<TController extends BaseControllerCRUDMethods> = {
    /** Applied to all routes generated by this factory. */
    all?: RequestHandler[];
    /** Applied only to the route bound to a specific controller method. */
    path?: Partial<Record<keyof TController, RequestHandler[]>>;
};

/**
 * Configuration for {@link createBaseRoutes}.
 */
export interface BaseRouteConfig<
    TController extends BaseControllerCRUDMethods = BaseControllerCRUDMethods
> {
    /** Instance of a class extending {@link BaseCRUDController}. */
    crudController: TController;
    /** Optional global or per-method {@link BaseRouteMiddleware}. */
    middlewareList?: BaseRouteMiddleware<TController>;
}

/**
 * Generates an {@link Router} with pre-configured CRUD endpoints.
 * * Features:
 * - Automatic {@link isAuth} injection.
 * - Async error wrapping via {@link asyncHandler}.
 * - Selective endpoint exclusion via `excludeKeys`.
 * @param config - The {@link BaseRouteConfig} containing the controller and middleware.
 * @param excludeKeys - Array of {@link BaseRoutePathKeys} to skip during registration.
 */
export const createBaseRoutes = <
    TController extends BaseControllerCRUDMethods
>(
    config: BaseRouteConfig<TController>,
    excludeKeys: BaseRoutePathKeys[] = [],
): Router => {
    const { crudController, middlewareList } = config;
    const { all: allMiddleware, path: pathMiddleware } = middlewareList || {};

    /** Helper to bind context and wrap the controller method. */
    const bind = (fn: keyof TController) =>
        asyncHandler(
            (crudController[fn] as (...args: any[]) => Promise<any>)
                .bind(crudController),
        );

    const router = express.Router();

    /** * Defined set of standard CRUD endpoints.
     * Note: 'slug' routes to {@link BaseControllerCRUDMethods.getBySlug}.
     */
    const routes: RoutePath<TController>[] = [
        { key: "all", method: "get", path: "/all", fn: "all" },
        { key: "paginated", method: "get", path: "/paginated", fn: "paginated" },
        { key: "create", method: "post", path: "/create", fn: "create" },
        { key: "get", method: "get", path: "/get/:_id", fn: "get" },
        { key: "slug", method: "get", path: "/slug/:slug", fn: "getBySlug" },
        { key: "update", method: "patch", path: "/update/:_id", fn: "update" },
        { key: "delete", method: "delete", path: "/delete/:_id", fn: "delete" },
        { key: "soft-delete", method: "delete", path: "/delete/:_id/soft", fn: "softDelete" },
        { key: "query", method: "get", path: "/query", fn: "query" },
    ];

    for (const { key, method, path, fn } of routes) {
        if (excludeKeys.includes(key)) {
            continue;
        }

        const middleware = [
            isAuth,
            ...(allMiddleware ?? []),
            ...(pathMiddleware?.[fn] ?? []),
        ];

        router[method](path, middleware, bind(fn));
    }

    return router;
};