export default [
    "Regular",
    "Premium",
    "VIP",
    "Recliner",
    "Loveseat",
    "Accessible",
    "Companion",
    "D-Box",
    "Haptic",
    "Extra-Legroom",
    "Balcony",
    "Cuddle Couch",
    "Pod",
    "Box",
    "Bean Bag",
    "Floor",
    "Budget",
    "Standing Space",
] as const;