export default interface ICloudinaryImage {
    public_id: string,
    secure_url: string,
    version: number,
    width: number,
    height: number,
    format: string,
    resource_type: string,
    bytes: number,
    type: string,
    etag: string,
    url: string,
    signature: string,
    original_filename: string,
}